INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (1, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (2, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (3, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (4, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (5, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (6, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (7, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (8, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 1, 10, 'economy', 'Места в первых рядах - не очень удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 2, 10, 'standart', 'Места выгодные по цене и удобные для просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 3, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 4, 10, 'comfort', 'Места в  центре зала  -самые лучшие для комфортного просмотра')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 5, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 6, 8, 'vip', 'Все места в VIP-залах - суперкомфортные кресла-реклайнеры')
INSERT INTO [dbo].[hall_row] (id_hall, number, capacity, category, description) VALUES (9, 7, 8, 'love', 'Парные диванчики  на последнем ряду для романтических свиданий')
SELECT * FROM hall_row